In [1]:
import numpy as np

In [29]:
A = np.random.random(12).reshape(3,4) * 100
print(A)

[[ 37.17990744  44.90707855  22.52348844  17.38452005]
 [ 85.50541532  83.9642251   37.69257928  65.3447264 ]
 [ 13.737134    70.36222367  46.10569769  87.70101326]]


In [30]:
cal = A.sum(axis=0)
print(cal)

[ 136.42245676  199.23352732  106.3217654   170.43025971]


In [34]:
percentage = 100 * (A / cal.reshape(1, 4))
print(percentage)

[[ 27.25350967  22.53992044  21.18426867  10.20037174]
 [ 62.67693556  42.14362223  35.45142345  38.34103551]
 [ 10.06955477  35.31645733  43.36430788  51.45859275]]
