In [1]:
import numpy as np

In [12]:
a = np.random.randn(5).reshape(5, 1)
print(a)
print(a.shape)

[[ 0.95307128]
 [-0.19295774]
 [ 0.67285148]
 [-0.71561692]
 [-1.35512772]]
(5, 1)


In [13]:
b = a.T
print(b)
print(b.shape)

[[ 0.95307128 -0.19295774  0.67285148 -0.71561692 -1.35512772]]
(1, 5)


In [14]:
c = np.dot(a, b)
print(c)
print(c.shape)

[[ 0.90834487 -0.18390248  0.64127542 -0.68203393 -1.29153332]
 [-0.18390248  0.03723269 -0.1298319   0.13808382  0.26148239]
 [ 0.64127542 -0.1298319   0.45272911 -0.4815039  -0.91179969]
 [-0.68203393  0.13808382 -0.4815039   0.51210757  0.96975232]
 [-1.29153332  0.26148239 -0.91179969  0.96975232  1.83637114]]
(5, 5)
